### ISSUE TITLE
Very slow performance with Java API

### ISSUE THREAD

**Issue by kjozsa** [datasonnet/datasonnet-mapper#121] opened 2023-06-02 14:01 UTC
We are utilizing DataSonnet in an integration project, using its Java API with OpenJDK17. It turns out that Datasonnet transformations are really slow for us, seriously holding back our integration platform's performance. 

Here is a basic example of what I measured:
```
        long start = System.currentTimeMillis();
        String input = Files.readString(Path.of(getClass().getResource("/sample/input.json").toURI()));
        String ds = Files.readString(Path.of(getClass().getResource("/sample/sample.ds").toURI()));
        Map<String, Document<?>> variables = new HashMap<>();
        logger.info("time: {} ms", System.currentTimeMillis() - start);

        Mapper mapper = new Mapper(ds, variables.keySet());
        logger.info("time: {} ms", System.currentTimeMillis() - start);

        Document<String> transform = mapper.transform(new DefaultDocument<>(input), variables, MediaTypeUtils.parseMediaType("application/json"));
        logger.info("time: {} ms", System.currentTimeMillis() - start);

        String result = transform.getContent();
        logger.info("time: {} ms", System.currentTimeMillis() - start);
```
outputs 
```
2023-06-02 15:52:52,927 INFO  [com.lot.int.sam.DataSonnetPlayground] (main) <>[][] time: 1 ms
2023-06-02 15:52:53,333 INFO  [com.lot.int.sam.DataSonnetPlayground] (main) <>[][] time: 408 ms
2023-06-02 15:52:53,400 INFO  [com.lot.int.sam.DataSonnetPlayground] (main) <>[][] time: 475 ms
2023-06-02 15:52:53,400 INFO  [com.lot.int.sam.DataSonnetPlayground] (main) <>[][] time: 475 ms
```
so the `new Mapper(..)` call **takes 407ms** and the actual transformation **takes another 67ms**.  

I'll attach the test input and the test transformation scripts to this ticket, but they are ~500 and ~100 lines long, nothing extreme I think.

Now to the questions.. Are we doing something obviously wrong here? Does this performance look okay, or at least acceptable according to your experiences? Can we do anything to speed up the transformations? Most importantly, is it possible to cache and reuse the Mapper object, so at least we save the huge instantiation time of the Mapper?

Thanks much in advance..
[input.json.txt](https://github.com/datasonnet/datasonnet-mapper/files/11635987/input.json.txt)
[sample.ds.txt](https://github.com/datasonnet/datasonnet-mapper/files/11635988/sample.ds.txt)

**Comment by javaduke** [comment] 2023-06-07 16:46
Hi @kjozsa , I was able to reproduce your test and I think I know where the bottleneck is, let me work on it and I will keep you posted.
In the meantime, can you please tell me a little bit more about what do you use datasonnet for, maybe a few more details about your project, etc. We have some plans for improving the datasonnet experience, adding more tools, expanding the language and libraries, and we'd really like to get some feedback from real users.

**Comment by javaduke** [comment] 2023-06-07 17:22
Hmm, I just ran some tests and it looks like only when mapper is instantiated for the first time, it takes about half a second. Consider this code:
```
        elapsed = System.currentTimeMillis();
        Mapper mapper = new Mapper(ds);
        elapsed = System.currentTimeMillis() - elapsed;
        logger.info("Mapper instantiation #1: {} ms", elapsed);

        elapsed = System.currentTimeMillis();
        mapper = new Mapper(ds);
        elapsed = System.currentTimeMillis() - elapsed;
        logger.info("Mapper instantiation #2: {} ms", elapsed);

        elapsed = System.currentTimeMillis();
        mapper = new Mapper("{ test: payload }");
        elapsed = System.currentTimeMillis() - elapsed;
        logger.info("Mapper instantiation #3: {} ms", elapsed);
```

The output was:

```
10:19:58.692 [main] INFO com.datasonnet.Issue121Test - Mapper instantiation #1: 483 ms
10:19:58.719 [main] INFO com.datasonnet.Issue121Test - Mapper instantiation #2: 27 ms
10:19:58.737 [main] INFO com.datasonnet.Issue121Test - Mapper instantiation #3: 18 ms
```

The transformation itself took about 64 milliseconds. 
I will definitely investigate it further but it seems like a workaround for now would be to have a dummy instance of a mapper created when your application starts.

**Comment by kjozsa** [comment] 2023-06-07 19:53
hi @javaduke, thanks for getting back to me on this. I was kind of giving up that someone will look into our issue.. 

We ended up having a workaround where we cache the Mapper instances for each datasonnet file. I wasn't sure if it's completely threadsafe, but I wrote a test where the same Mapper is used parallely by 1000 concurrent threads and I could not make it fail, so I assume it is threadsafe afterall.. (please confirm if you can). This way the average transformation time was down to ~7ms, which is acceptable for our usecase. If you can found a way to squeeze down latencies (even initial Mapper creation) and speed up DS transformations, that would help us a lot.

Speaking of which, we are doing system integration work for a high profile client in Asia. We are replacing an established Mulesoft platform with a custom Camel-based integration stack running on Quarkus and deployed to Kubernetes. Datasonnet was chosen by my team as the primary data transformation language, because it's very similar to Mulesoft's Dataweave language (https://dataweave.mulesoft.com/) and the DS transformations are really elegant. Performance however, given the nature of this application is really important, as our integration platform's latency must stay real low to be usable.. 

One of the improvements we have made is that we implemented a clone of the Dataweave Playground (https://dataweave.mulesoft.com/learn/dataweave) for Datasonnet, basically a web UI which makes it a snap to develop and test DS scripts with sample inputs. If that sounds interesting to you, we can separate and opensource this codebase, so you can either refer to it or integrate with your base project, as you wish.

**Comment by javaduke** [comment] 2023-06-08 18:27
I think I know exactly what's going on there. The DataSonnet parser has to initialize when the Mapper is instantiated for the first time, and it loads all classes and objects that represent the DataSonnet expressions. This is only done once, after that it is cached in memory so all subsequent initializations are fast. So there's not much we can do here, and I think the best option for you would be to initialize a Mapper once or have a dummy static instance.

Please let me know if you need any further information or assistance, otherwise I will close this ticket.

**Comment by d4ljoyn** [comment] 2023-08-14 04:10
@kjozsa That is interesting I am investigating exactly the same situation -- moving from existing MuleSoft integrations to an apache camel stack.  I agree that of the available options datasonnet is one of the most elegant and closest in kind to dataweave.  I would love to see your datasonnet playground in action.  We will implement the "stupid workaround" to reduce initialization times for now and I appreciate this thread @javaduke

**Comment by kjozsa** [comment] 2023-08-15 08:48
@d4ljoyn I've dropped you an email to your gmail address, let's continue discussions there.

**Closed** 2023-10-20 18:06 UTC
